#!/bin/bash

while true;do
	echo "Eu sou o homem que vai se tornar o rei dos piratas! (MONKEI.D LUFFY)"

	echo 'a - Liste apenas os diretórios de uma pasta'
	echo 'b - Liste apenas os arquivos executáveis'
	echo 'c - Liste apenas os links simbólicos'
	echo 'x - Saia do script'


	read -p "Escolha uma alternativa: " escolha
	case $opcao in
		"a") read -p "Escolha a pasta para listar os diretórios: " dir
		     ls -al $dir | grep "^d"
		     ;;
		"b") read -p "Escolha a pasta para listar os arquivos executáveis: " arqv
			for i in $(ls $arqv);
			do
				if [ -x $i ];then
					echo $i
				fi
			done;;
		"c") read -p "Escolha a pasta para listar os links simbolicos: " arqv
			for i in $(ls $arqv);
			do
				if [ -h $arqv ];then
					echo $i
				fi
			done;;
			
		"x") 	clear
			
			break;;
	esac

done
